### ISSUE TITLE
Jarvis-Light-Lifx ne fonctionne pas sous OSX

### ISSUE THREAD

**Issue by Latlantis** [alexylem/jarvis-plugin#3]
Bonsoir, tout est dans le titre, en fait à l'installation, il essaye de lancer un "apt-get" qui évidemment n'existe pas sous OSX. Pourriez-vous me guider svp ? j'aimerais le faire fonctionner sous Mac. Merci beaucoup :-)

**Comment by alexylem** [comment]
Merci de créer un ticket sur le repo du plugin en question:
https://github.com/devauxa/jarvis-light-lifx/issues/new
