### ISSUE TITLE
Allow code search on Jarvis plugin repositories

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis-plugin#7]
By using the procedure described [here](http://domotiquefacile.fr/jarvis/content/publish-your-plugin)  we have a fork. Github does not allow code search on fork repositories, which might be annoying.

I would recommend to:

1. Clone this repo `git clone https://github.com/alexylem/jarvis-plugin`
2. Rename the folder and move inside `mv jarvis-plugin/ jarvis-new-name`, `cd jarvis-new-name`
3. Create a [new Github](https://github.com/new) repository
4. Remove jarvis-plugin git remote `git remote remove origin`
5. Add the new remote `git remote add origin git@github.com:UserName/jarvis-new-name.git`.
This command is displayed by Github after the creation of the repo.
6. Push the code to the new repo `git push`

**Comment by alexylem** [comment]
Hello @Oliv4945 
Yes you are right, I initially chose the fork method to:
1) Easy the process as much as possible
2) Have a counter of fork from the jarvis-plugin repo
I will update the site accordingly, hope it will not make the process more complex to non `git` users.

**Comment by Oliv4945** [comment]
I understand the counter. For non git users if they write a plugin they should be able to follow the documentation. 
Nevertheless maybe you can list both ways ?

**Comment by alexylem** [comment]
No it's ok I'll change it to your method.
There is also another advantage, I will be able to propose pull requests to plugins, today I can't because they are forks of mine...

**Comment by alexylem** [comment]
I am thinking to automate this procedure from within Jarvis:

Menu Plugins > Create a plugin
```shell
$> Your github username? sign-up at https://github.com/join
USER
$> cd plugins_installed
$> git clone https://github.com/alexylem/jarvis-plugin
$> Name of your plugin? (sanitized)
jarvis-REPO
$> mv jarvis-plugin jarvis-REPO
$> cd jarvis-REPO
$> git remote remove origin
$> curl -u 'USER' https://api.github.com/user/repos -d '{"name":"REPO"}'
Enter host password for user 'USER': ******
# bunch of JSON output
$> git remote add origin git@github.com:USER/REPO.git
$> git push origin master
$> cd ../../
```
It fully works without having to open the browse once:
https://github.com/alexylem/test-repo has been created the above way.

Once the plugin is ready & tested, to push changes and publish on the store
```
$> cd plugins_installed/jarvis-REPO
$> git push
$> cd ../../
```
And register the plugin on the store:
http://domotiquefacile.fr/jarvis/node/add/plugin

But I may provide a menu option for this.
This way no more long procedure to follow 😄  what do you think?

**Comment by alexylem** [comment]
I also found how to activate issues by default and add a repo description. Working on it.

**Comment by alexylem** [comment]
@Oliv4945 
I have implemented it on the beta branch.
Can you please give it a try:
Menu Jarvis > Plugin > Create a plugin
Go though the steps you should end up with a fresh preconfigured plugin locally linked to a new repo on your github account.
I still need to adapt the site webpage, but would be nice if you could give it a try first.
Thanks,
Alex.

**Comment by Oliv4945** [comment]
@alexylem : Nice development ! I will test it soon :-)

**Comment by Oliv4945** [comment]
@alexylem : It works, thank you :+1:

**Comment by Oliv4945** [comment]
Tested with a [real plugin](https://github.com/Oliv4945/jarvis-air-quality-france), works wells !
