### ISSUE TITLE
jarvis plugin python

### ISSUE THREAD

**Issue by djlive** [alexylem/jarvis-plugin#9]
Bonjour je suis désoler  de vous déranger, mais je n'arrive pas a créer mon plugin : Commande =>jarvis allume lumiere == execute un fichier python en bash pour piloter les gpio.
J'ai d'autre programme python que je souhaite executer par jarvis a la voix mais je n'y arrive pas.
Pouvez-vous m'aidez ?
Merci

**Comment by alexylem** [comment]
Pas besoin de plugin pour ca, juste une simple commande.
Doc: http://domotiquefacile.fr/jarvis/content/commands
Exemple:
**Jarvis Menu > Commands**
```shell
*ALLUME*LUMIERE*==python /path/to/your/python/script.py && say "Voilà"
```

**Comment by djlive** [comment]
ok merci je vais m'y ateler

**Comment by djlive** [comment]
super cool ça fonctionne
